= Mint Lang Explorations
:source-highlighter: prettify
:source-language: mint
Bill Tihen (Mint 0.7.1)
:sectnums:
:toc:
:toclevels: 4
:toc-title: Contents

:description: Exploring Mint's Features
:keywords: Mint Language
:imagesdir: ./images

**link:index.html[Mint Page]**

== Mint-Bulma Tutorial

Adding an external CSS: in this case *Bulma* https://bulma.io/

This should allow us to greatly shorten our code to focus on the logic not the format!

=== Intitialize a project:

```bash
$ mint-lang init count_bulma
$ cd count_bulma 
$ mkdir assets
$ touch assets/head.html
$ mint-lang start
```

open `http://localhost:3000`

be sure you see: `Hello Mint!`

=== Add Bulma and Fontawesome

We will control our counter values and save the state centrally (this Store resets with every page reload / new connection)

.code/mint/src/count_bulma/assets/head.html
[html,source,linenums]
----
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

<!-- adding Bulma CSS -->
<link rel="stylesheet" 
  href="https://cdn.jsdelivr.net/npm/bulma@0.8.0/css/bulma.min.css"
  crossorigin="anonymous">

<!-- add Litera Theme -->
<link rel="stylesheet" 
  href="https://unpkg.com/bulmaswatch/litera/bulmaswatch.min.css">

<!-- Add Fontawesome -->
<link rel="stylesheet" 
  href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" 
  integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" 
  crossorigin="anonymous">
----

Now we have to tell mint to use this file - you do this by adding:
```json
"application": {
    "head": "assets/head.html"
  },
```
to the mint.json file -- so now the file looks like:

.code/mint/src/count_bulma/mint.json
[html,source,linenums]
----
{
  "name": "bulma_count",
  "source-directories": [
    "source"
  ],
  "application": {
    "head": "assets/head.html"
  },
  "test-directories": [
    "tests"
  ]
}
----

=== Counter Component

Now you can see the code is focused on the logic and CSS is mostly external.

NOTE: We are still using the CounterStore from the previous exploration.

.code/mint/src/count_bulma/source/Counter.mint
[source,linenums]
----
component Counter {

  connect Counter.Store exposing {
    count,
    increment as incrementCounter,
    decrement as decrementCounter
  }

  fun handleDecrement (event : Html.Event) : Promise(Never, Void) {
    decrementCounter()
  }

  fun handleIncrement (event : Html.Event) : Promise(Never, Void) {
    incrementCounter()
  }

  fun render : Html {
    <nav class="panel">
      <p class="panel-heading">
        <{ "Mint Counter" }>
      </p>
      <p class="panel-tabs">
        <a>
          <button class="button is-medium is-warning" onClick={handleDecrement}>
            <i class="fas fa-minus"></i>
          </button>
        </a>
        <a>
          <p class="title is-3">
            <{ "Count: #{count}" }>
          </p>
        </a>
        <a>
          <button class="button is-medium is-success" onClick={handleIncrement}>
            <i class="fas fa-plus"></i>
          </button>
        </a>
      </p>
    </nav>
  }
}
----

=== Add our Counter to Main

.code/mint/src/count_bulma/source/Main.mint
[source,linenums]
----
component Main {

  style centerAll {
    font-family: sans;
    font-weight: bold;
    font-size: 50px;

    justify-content: center;
    align-items: center;
    display: flex;
    height: 100vh;
    width: 100vw;
  }

  fun render : Html {
    <div::centerAll class="container is-fluid">
      <Counter/>
    </div>
  }

}
----

* here in `Main` we used Mint CSS in `<div::centerAll class="container is-fluid">` -- so we can now use both Bulma class tags and Mint to override.
* you must stop mint and restart -- to load the new assets.

Now open `http://localhost:3000`

be sure you see: 
* `Count:` centered vertically and horizontally in a new font
* and `+` and `-` buttons formatted with Fontawesome Icons
* the buttons should be rounded using the *litera* Bulma theme.

**link:index.html[Mint Page]**